[
  {
    _readableState: "1",
    _events: "2",
    _eventsCount: 1,
    socket: "3",
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: "4",
    complete: true,
    rawHeaders: "5",
    rawTrailers: "6",
    aborted: false,
    upgrade: false,
    url: "7",
    method: "8",
    statusCode: null,
    statusMessage: null,
    client: "3",
    _consuming: false,
    _dumped: false,
    baseUrl: "9",
    originalUrl: "7",
    _parsedUrl: "10",
    params: "11",
    query: "12",
    res: "13",
    _parsedOriginalUrl: "14",
    route: "15",
  },
  {
    objectMode: false,
    highWaterMark: 16384,
    buffer: "16",
    length: 0,
    pipes: "17",
    flowing: null,
    ended: true,
    endEmitted: false,
    reading: false,
    constructed: true,
    sync: true,
    needReadable: false,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: true,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: "18",
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: true,
    decoder: null,
    encoding: null,
  },
  {},
  {
    connecting: false,
    _hadError: false,
    _parent: null,
    _host: null,
    _readableState: "19",
    _events: "20",
    _eventsCount: 8,
    _writableState: "21",
    allowHalfOpen: true,
    _sockname: null,
    _pendingData: null,
    _pendingEncoding: "9",
    server: "22",
    _server: "22",
    parser: "23",
    _paused: false,
    _httpMessage: "13",
  },
  "1.1",
  [
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "30",
    "31",
    "32",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "37",
    "39",
    "40",
    "41",
    "42",
    "43",
    "44",
    "45",
    "46",
    "47",
    "48",
    "49",
    "50",
    "51",
    "52",
    "53",
    "54",
    "55",
    "56",
    "57",
    "58",
  ],
  [],
  "/",
  "GET",
  "",
  {
    protocol: null,
    slashes: null,
    auth: null,
    host: null,
    port: null,
    hostname: null,
    hash: null,
    search: null,
    query: null,
    pathname: "7",
    path: "7",
    href: "7",
    _raw: "7",
  },
  {},
  {},
  {
    _events: "59",
    _eventsCount: 1,
    outputData: "60",
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: false,
    chunkedEncoding: false,
    shouldKeepAlive: true,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: true,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: "9",
    finished: false,
    _headerSent: false,
    _closed: false,
    socket: "3",
    _header: null,
    _keepAliveTimeout: 5000,
    req: "0",
    _sent100: false,
    _expect_continue: false,
    locals: "61",
  },
  {
    protocol: null,
    slashes: null,
    auth: null,
    host: null,
    port: null,
    hostname: null,
    hash: null,
    search: null,
    query: null,
    pathname: "7",
    path: "7",
    href: "7",
    _raw: "7",
  },
  { path: "7", stack: "62", methods: "63" },
  { head: null, tail: null, length: 0 },
  [],
  "utf8",
  {
    objectMode: false,
    highWaterMark: 16384,
    buffer: "64",
    length: 0,
    pipes: "65",
    flowing: true,
    ended: false,
    endEmitted: false,
    reading: true,
    constructed: true,
    sync: false,
    needReadable: true,
    emittedReadable: false,
    readableListening: false,
    resumeScheduled: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: true,
    destroyed: false,
    errored: null,
    closed: false,
    closeEmitted: false,
    defaultEncoding: "18",
    awaitDrainWriters: null,
    multiAwaitDrain: false,
    readingMore: false,
    decoder: null,
    encoding: null,
  },
  { end: "66", close: "67" },
  {
    objectMode: false,
    highWaterMark: 16384,
    finalCalled: false,
    needDrain: false,
    ending: false,
    ended: false,
    finished: false,
    destroyed: false,
    decodeStrings: false,
    defaultEncoding: "18",
    length: 0,
    writing: false,
    corked: 0,
    sync: true,
    bufferProcessing: false,
    writecb: null,
    writelen: 0,
    afterWriteTickInfo: null,
    buffered: "68",
    bufferedIndex: 0,
    allBuffers: true,
    allNoop: true,
    pendingcb: 0,
    constructed: true,
    prefinished: false,
    errorEmitted: false,
    emitClose: false,
    autoDestroy: true,
    errored: null,
    closed: false,
    closeEmitted: false,
  },
  {
    _events: "69",
    _eventsCount: 2,
    _connections: 2,
    _handle: "70",
    _usingWorkers: false,
    _workers: "71",
    _unref: false,
    allowHalfOpen: true,
    pauseOnConnect: false,
    httpAllowHalfOpen: false,
    timeout: 0,
    keepAliveTimeout: 5000,
    maxHeadersCount: null,
    headersTimeout: 60000,
    requestTimeout: 0,
    _connectionKey: "72",
  },
  {
    _headers: "73",
    _url: "9",
    socket: "3",
    incoming: "0",
    outgoing: null,
    maxHeaderPairs: 2000,
    _consumed: true,
  },
  "Host",
  "localhost:3000",
  "Connection",
  "keep-alive",
  "Cache-Control",
  "max-age=0",
  "sec-ch-ua",
  '"Google Chrome";v="93", " Not;A Brand";v="99", "Chromium";v="93"',
  "sec-ch-ua-mobile",
  "?0",
  "sec-ch-ua-platform",
  '"macOS"',
  "DNT",
  "1",
  "Upgrade-Insecure-Requests",
  "User-Agent",
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36",
  "Accept",
  "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
  "Sec-Fetch-Site",
  "none",
  "Sec-Fetch-Mode",
  "navigate",
  "Sec-Fetch-User",
  "?1",
  "Sec-Fetch-Dest",
  "document",
  "Accept-Encoding",
  "gzip, deflate, br",
  "Accept-Language",
  "en-GB,en-US;q=0.9,en;q=0.8",
  "If-None-Match",
  'W/"74d-17c07d09e14"',
  "If-Modified-Since",
  "Tue, 21 Sep 2021 10:04:44 GMT",
  {},
  [],
  {},
  ["74"],
  { get: true },
  { head: null, tail: null, length: 0 },
  [],
  [null, null],
  [null, null],
  [],
  {},
  { reading: false },
  [],
  "6::::3000",
  [],
  { name: "75", keys: "76", regexp: "77", method: "78" },
  "<anonymous>",
  [],
  { fast_star: false, fast_slash: false },
  "get",
];
